# Generated by Django 4.1.13 on 2024-07-12 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_live', models.BooleanField()),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='course_pictures/')),
                ('course_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(max_length=100)),
                ('TeacherEmail', models.EmailField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentname', models.CharField(max_length=100)),
                ('StudentEmail', models.EmailField(max_length=100)),
                ('StudentPassword', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=100)),
                ('assignment_description', models.TextField()),
                ('due_date', models.DateField()),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KachyaApp.course')),
            ],
        ),
    ]
