# Generated by Django 4.1.13 on 2024-07-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_live', models.BooleanField()),
                ('course_picture', models.ImageField(blank=True, null=True, upload_to='course_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=100)),
                ('assignment_description', models.TextField()),
                ('due_date', models.DateField()),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KachyaApp.course')),
            ],
        ),
    ]
