# Generated by Django 4.1.13 on 2024-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_assignment',
            field=models.IntegerField(null=True),
        ),
    ]
