# Generated by Django 4.1.13 on 2024-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0002_course_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_assignment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assignment_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course_taken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assgined_course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_live',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='TeacherEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='Teachername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
