# Generated by Django 4.1.13 on 2024-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0004_course_course_price_studentprofile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nextclassSchedule',
            field=models.TimeField(null=True),
        ),
    ]
