# Generated by Django 4.1.13 on 2024-07-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0005_teacherprofile_nextclassschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='nextclassSchedule',
            field=models.DateTimeField(null=True),
        ),
    ]
