# Generated by Django 4.1.13 on 2024-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0006_alter_teacherprofile_nextclassschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_requirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_teaching',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
