# Generated by Django 4.1.13 on 2024-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0007_course_course_requirement_course_teacher_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_small_description',
            field=models.TextField(null=True),
        ),
    ]
