# Generated by Django 4.1.13 on 2024-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0008_course_course_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
