# Generated by Django 4.1.13 on 2024-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KachyaApp', '0009_assignment_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
